# Generated by Django 3.1.2 on 2020-10-04 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_no', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 't_author',
            },
        ),
        migrations.CreateModel(
            name='AuthorDetails',
            fields=[
                ('ad_no', models.AutoField(primary_key=True, serialize=False)),
                ('ad_name', models.CharField(max_length=30)),
                ('ad_introduce', models.TextField()),
            ],
            options={
                'db_table': 't_authordetails',
            },
        ),
        migrations.CreateModel(
            name='Dynasty',
            fields=[
                ('dynasty_no', models.AutoField(primary_key=True, serialize=False)),
                ('dynasty_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 't_dynasty',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_no', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 't_tag',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('title_no', models.AutoField(primary_key=True, serialize=False)),
                ('title_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 't_title',
            },
        ),
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('poetry_no', models.AutoField(primary_key=True, serialize=False)),
                ('poetry_title', models.CharField(max_length=30)),
                ('poetry_text', models.TextField()),
                ('poetry_translation', models.TextField()),
                ('poetry_annotation', models.TextField()),
                ('poetry_appreciation', models.TextField()),
                ('poetry_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poetry.author')),
                ('poetry_dynasty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poetry.dynasty')),
                ('poetry_tag', models.ManyToManyField(to='poetry.Tag')),
            ],
            options={
                'db_table': 't_poetry',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='author_dynasty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poetry.dynasty'),
        ),
    ]
